version: '3.7'
services:
  django:
    build: .
    restart: always
    environment:
      PORT: 5000
      DB_NAME: test
      DB_USER: django
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: secret-key
    ports:
     - 5000:5000
    volumes:
     - static:/app/static
    depends_on:
     - db

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
    volumes:
      - psql:/var/lib/postgresql/data/

volumes:
  static:
  psql:
