name: Build

on:
 workflow_run:
   workflows: ["All"]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: $GITHUB_SHA
